DROP TABLE MGCCOP.CANVAS_ACCOUNTS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_ACCOUNTS
(
  ACCOUNT_ID                VARCHAR2(20 BYTE),
  ACCOUNT_NAME              VARCHAR2(100 BYTE),
  ACCOUNT_STATUS            VARCHAR2(20 BYTE),
  ACCOUNT_INITIAL_BATCH_ID  VARCHAR2(50 BYTE),
  ACCOUNT_LAST_BATCH_ID     VARCHAR2(50 BYTE),
  ACCOUNT_PARENT_ID         VARCHAR2(20 BYTE)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP TABLE MGCCOP.CANVAS_ADD_TERMS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_ADD_TERMS
(
  ADD_TERM  VARCHAR2(6 CHAR)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP TABLE MGCCOP.CANVAS_DEPT_SUBJ CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_DEPT_SUBJ
(
  SUBJ_CODE  VARCHAR2(5 CHAR),
  SUBJ_DEPT  VARCHAR2(20 CHAR)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

DROP TABLE MGCCOP.CANVAS_DEPTS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_DEPTS
(
  DEPT_ACCT_ID  VARCHAR2(20 CHAR),
  DEPT_NAME     VARCHAR2(100 CHAR)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE MGCCOP.CANVAS_ENRL
 DROP PRIMARY KEY CASCADE;

DROP TABLE MGCCOP.CANVAS_ENRL CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_ENRL
(
  ENRL_TERM              VARCHAR2(6 BYTE),
  ENRL_CRN               VARCHAR2(5 BYTE),
  ENRL_PIDM              NUMBER(8),
  ENRL_SECTION_ID        VARCHAR2(20 BYTE),
  ENRL_ROLE              VARCHAR2(20 BYTE),
  ENRL_STATUS            VARCHAR2(20 BYTE),
  ENRL_LAST_BATCH_ID     VARCHAR2(50 BYTE),
  ENRL_INITIAL_BATCH_ID  VARCHAR2(50 BYTE),
  ENRL_ID                VARCHAR2(9 BYTE)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MGCCOP.PK_ENRL ON MGCCOP.CANVAS_ENRL
(ENRL_TERM, ENRL_CRN, ENRL_PIDM, ENRL_ROLE)
LOGGING
TABLESPACE MGCCC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX MGCCOP.PK_ENRL_TERM ON MGCCOP.CANVAS_ENRL
(ENRL_TERM)
LOGGING
TABLESPACE MGCCC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MGCCOP.CANVAS_ENRL ADD (
  CONSTRAINT PK_ENRL
  PRIMARY KEY
  (ENRL_TERM, ENRL_CRN, ENRL_PIDM, ENRL_ROLE)
  USING INDEX MGCCOP.PK_ENRL);
  
  DROP TABLE MGCCOP.CANVAS_EXCL_TERMS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_EXCL_TERMS
(
  EXCL_TERM  VARCHAR2(6 CHAR)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE MGCCOP.CANVAS_SECTIONS
 DROP PRIMARY KEY CASCADE;

DROP TABLE MGCCOP.CANVAS_SECTIONS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_SECTIONS
(
  SECTION_TERM              VARCHAR2(6 BYTE),
  SECTION_CRN               VARCHAR2(5 BYTE),
  SECTION_ID                VARCHAR2(20 BYTE),
  SECTION_SNAME             VARCHAR2(100 BYTE),
  SECTION_LNAME             VARCHAR2(100 BYTE),
  SECTION_ACCOUNT           VARCHAR2(10 BYTE),
  SECTION_STATUS            VARCHAR2(20 BYTE),
  SECTION_SDATE             DATE,
  SECTION_EDATE             DATE,
  SECTION_LAST_BATCH_ID     VARCHAR2(50 BYTE),
  SECTION_INITIAL_BATCH_ID  VARCHAR2(50 BYTE)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MGCCOP.PK_SECTIONS ON MGCCOP.CANVAS_SECTIONS
(SECTION_TERM, SECTION_CRN)
LOGGING
TABLESPACE MGCCC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX MGCCOP.PK_SECTION_TERM ON MGCCOP.CANVAS_SECTIONS
(SECTION_TERM)
LOGGING
TABLESPACE MGCCC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MGCCOP.CANVAS_SECTIONS ADD (
  CONSTRAINT PK_SECTIONS
  PRIMARY KEY
  (SECTION_TERM, SECTION_CRN)
  USING INDEX MGCCOP.PK_SECTIONS);
  
  ALTER TABLE MGCCOP.CANVAS_USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE MGCCOP.CANVAS_USERS CASCADE CONSTRAINTS;

CREATE TABLE MGCCOP.CANVAS_USERS
(
  USER_PIDM              NUMBER(8),
  USER_ID                VARCHAR2(9 BYTE),
  USER_PASSWORD          VARCHAR2(256 BYTE),
  USER_FNAME             VARCHAR2(60 BYTE),
  USER_LNAME             VARCHAR2(60 BYTE),
  USER_EMAIL             VARCHAR2(128 BYTE),
  USER_STATUS            VARCHAR2(10 BYTE),
  USER_LAST_BATCH_ID     VARCHAR2(50 BYTE),
  USER_INITIAL_BATCH_ID  VARCHAR2(50 BYTE)
)
TABLESPACE MGCCC
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX MGCCOP.PK_USERS ON MGCCOP.CANVAS_USERS
(USER_PIDM)
LOGGING
TABLESPACE MGCCC
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE MGCCOP.CANVAS_USERS ADD (
  CONSTRAINT PK_USERS
  PRIMARY KEY
  (USER_PIDM)
  USING INDEX MGCCOP.PK_USERS);
